spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
